[package]
name = "cargo-and-crates"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0 # opt-level no of optimizations rust will apply to your code

 # more optimizations, more compile time
[profile.release]
opt-level = 3

[dependencies]
