[package]
name = "jks-guessing-game"
version = "0.1.0"
edition = "2021"
description = "A fun game where you can what number the computer has chosen."
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.9.0"